import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export async function POST(request) {
  try {
    const { text } = await request.json();

    if (!text || text.trim().length === 0) {
      return Response.json(
        { error: 'Please provide text to analyze.' },
        { status: 400 }
      );
    }

    if (text.length > 5000) {
      return Response.json(
        { error: 'Text is too long. Maximum 5000 characters allowed.' },
        { status: 400 }
      );
    }

    if (text.trim().length < 50) {
      return Response.json(
        { error: 'Text is too short. Please provide at least 50 characters for meaningful analysis.' },
        { status: 400 }
      );
    }

    const prompt = `You are an expert in detecting AI-generated content and analyzing text originality. Analyze the following text and respond ONLY with valid JSON.

Text to analyze:
"""
${text.trim()}
"""

Analyze the text for these aspects:
1. **AI Detection**: Likelihood the text was generated by an AI model (ChatGPT, Claude, Gemini, etc.). Look for: overly polished phrasing, generic openings/closings, balanced symmetric paragraphs, lack of personal voice, predictable vocabulary, perfect grammar with bland word choice, common AI patterns like "In today's world", "It's important to note", "Furthermore", etc.

2. **Originality**: Score how unique and original the writing appears. Lower score = more likely templated/copied. Higher score = unique voice and ideas.

3. **Cliche Phrases**: Identify common cliched, templated, or overused phrases in the text (e.g., "at the end of the day", "thinking outside the box", "in this day and age", "a wide variety of", "plays a crucial role").

4. **Suspicious Sections**: Identify specific sentences or short passages that seem suspicious (overly polished compared to rest, sudden style change, sounds copy-pasted, generic encyclopedia-style writing). For each, give the exact text snippet and a reason.

Respond ONLY with valid JSON in this exact format (no markdown, no explanation):
{
  "aiDetectionScore": <number 0-100>,
  "originalityScore": <number 0-100>,
  "verdict": "<one short sentence summary>",
  "clichePhrases": ["<phrase1>", "<phrase2>", ...],
  "suspiciousSections": [
    { "text": "<exact snippet from text>", "reason": "<why suspicious>" }
  ]
}

Guidelines:
- aiDetectionScore: 0 = clearly human-written, 100 = clearly AI-generated
- originalityScore: 0 = highly templated/generic, 100 = unique original voice
- Keep clichePhrases array empty if none found (max 10)
- Keep suspiciousSections array empty if none found (max 5)
- Verdict should be one concise sentence`;

    const message = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1024,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    const raw = message.content[0].text.trim();

    let parsed;
    try {
      const jsonMatch = raw.match(/\{[\s\S]*\}/);
      const jsonText = jsonMatch ? jsonMatch[0] : raw;
      parsed = JSON.parse(jsonText);
    } catch (parseError) {
      console.error('Plagiarism AI parse error:', parseError, raw);
      return Response.json(
        { error: 'Failed to parse AI analysis. Please try again.' },
        { status: 500 }
      );
    }

    const result = {
      aiDetectionScore: Math.max(0, Math.min(100, Number(parsed.aiDetectionScore) || 0)),
      originalityScore: Math.max(0, Math.min(100, Number(parsed.originalityScore) || 0)),
      verdict: String(parsed.verdict || 'Analysis complete.'),
      clichePhrases: Array.isArray(parsed.clichePhrases) ? parsed.clichePhrases.slice(0, 10).map(String) : [],
      suspiciousSections: Array.isArray(parsed.suspiciousSections)
        ? parsed.suspiciousSections.slice(0, 5).map((s) => ({
            text: String(s.text || ''),
            reason: String(s.reason || ''),
          })).filter((s) => s.text.length > 0)
        : [],
    };

    return Response.json(result);

  } catch (error) {
    console.error('Plagiarism AI API Error:', error);
    return Response.json(
      { error: 'AI analysis failed. Please try again.' },
      { status: 500 }
    );
  }
}
