import PlagiarismCheckerClient from './PlagiarismCheckerClient';
import AdSlot from '@/components/AdSlot';
import FAQSection from '@/components/SEO/FAQSection';
import HowToUse from '@/components/SEO/HowToUse';
import LongContent from '@/components/SEO/LongContent';
import ToolSchema from '@/components/SEO/ToolSchema';
import { Type, Sparkles, Search, ShieldCheck } from 'lucide-react';

export const metadata = {
  title: 'Free Plagiarism Checker - AI Detection & Web Source Finder | MakerSilo',
  description: 'Free hybrid plagiarism checker that combines AI detection with live web search. Detect AI-generated content, find matching web sources, and check originality. No sign-up required.',
  keywords: 'plagiarism checker, free plagiarism checker, AI detector, AI content detector, originality checker, plagiarism detector, ChatGPT detector, Claude detector, AI writing detector, free originality check, web plagiarism search',
  openGraph: {
    title: 'Free Plagiarism Checker - AI Detection & Web Source Finder',
    description: 'Detect AI-generated content and find matching web sources. Free hybrid plagiarism checker powered by AI and live web search.',
    type: 'website',
  },
};

const steps = [
  { icon: Type, title: 'Paste Your Text', description: 'Paste up to 5,000 characters of text into the input box. Works for essays, articles, blog posts, and more.' },
  { icon: Sparkles, title: 'AI Analyzes', description: 'Claude AI evaluates your text for AI-generation patterns, originality, cliches, and suspicious sections in seconds.' },
  { icon: Search, title: 'Web Searches Live', description: 'The most distinctive sentences are searched on the live web (via Brave Search) to find any actual matching sources.' },
  { icon: ShieldCheck, title: 'Get Combined Report', description: 'Review your AI Detection score, Originality score, Web Match score, and overall risk level with full source details.' },
];

const faqs = [
  { q: 'How does this plagiarism checker work?', a: 'Our checker uses a hybrid two-pronged approach. First, Claude AI analyzes your text for patterns common in AI-generated content (overly polished phrasing, generic structure, predictable vocabulary) and identifies templated cliches. Second, it extracts the most distinctive sentences from your text and searches them on the live web using Brave Search to find any actual matching sources. You get a combined report with both AI analysis and real web matches.' },
  { q: 'Is it really free? Are there hidden limits?', a: 'Yes, completely free. No sign-up, no account, no credit card. The only limit is 5,000 characters per check (about 800-1000 words), which is enough for most essays, articles, and blog posts. There is no daily check limit for users.' },
  { q: 'Can it detect ChatGPT, Claude, or Gemini AI writing?', a: 'Yes. The AI Detection score specifically looks for patterns common in text generated by large language models like ChatGPT, Claude, Gemini, and similar tools. It identifies overly balanced paragraph structures, generic transitions ("In today\u2019s world", "It\u2019s important to note"), perfect grammar with bland word choice, and other LLM signatures. However, no AI detector is 100% accurate \u2014 use the score as guidance, not absolute proof.' },
  { q: 'How is this different from Turnitin or Grammarly?', a: 'Turnitin and Grammarly Premium have access to massive proprietary academic databases (papers, journals, student submissions) that we do not have. They are better for academic plagiarism. Our tool focuses on what is publicly available on the web (covering most copy-paste plagiarism from articles, blogs, websites) plus AI-generated content detection. For a free tool, we cover the majority of plagiarism cases and add AI detection that paid tools often charge extra for.' },
  { q: 'What does the Combined Risk score mean?', a: 'The Combined Risk score is a weighted average of three factors: AI Detection (40% weight), lack of originality (30%), and web matches (30%). A score of 0-19% means Original, 20-39% Low Risk, 40-69% Medium Risk, and 70-100% High Risk. Use it as a quick at-a-glance indicator, but always review the detailed AI Analysis and Web Sources tabs for full context.' },
  { q: 'Is my text saved or used to train AI?', a: 'No. Your text is sent directly to the AI model and search engine for processing, then discarded. We do not store, log, or save your input text. Your privacy is protected. The AI models we use (Claude) also do not train on user inputs through their API.' },
  { q: 'Why does the web search sometimes show 0 matches even for copied text?', a: 'A few reasons: (1) The web search uses exact-phrase matching with quoted sentences, so even small wording changes can hide a match. (2) The source might be behind paywalls, in PDFs, or otherwise not indexed by Brave Search. (3) The text may be from a niche source or a printed book. The AI Detection and Originality scores help catch what web search misses.' },
];

const longContent = `The Free Plagiarism Checker is a hybrid tool that combines two complementary approaches to give you the most complete originality analysis possible without paying for a subscription. By pairing advanced AI detection with live web search, the checker can identify both copied content (lifted from articles, blogs, or websites) and AI-generated content (written by ChatGPT, Claude, Gemini, or similar models) \u2014 something most free tools cannot do at the same time.

Plagiarism today comes in many forms. The most obvious is direct copy-paste, where someone takes text verbatim from another source. Our web search component handles this case by extracting the most distinctive sentences from your text and querying them on the live web with exact-phrase matching. If a sentence appears verbatim on a public web page, you will see it in the Web Sources panel with a direct link to the source URL, the page title, and the surrounding context.

A newer form of plagiarism is AI-generated content. Students and writers are increasingly using ChatGPT, Claude, and Gemini to generate essays, articles, and reports. While not technically plagiarism in the traditional sense, AI-generated content is often prohibited in academic and professional contexts. Our AI Detection score evaluates your text for patterns characteristic of large language model output: overly polished phrasing without natural variation, balanced symmetric paragraph structures, generic universal openings ("In today\u2019s world", "Throughout history"), predictable vocabulary, perfect grammar coupled with bland word choice, and frequent use of transition words like "moreover," "furthermore," and "it is important to note."

The Originality Score measures how unique and distinctive your writing voice is. Highly templated text \u2014 the kind that follows obvious essay structures, uses overused phrases, and feels like it could have been written by anyone \u2014 scores low. Text with a clear personal voice, unique word choices, and original ideas scores high. This is independent of whether the text is plagiarized or AI-generated; even original human writing can be unoriginal in style.

The Cliche Phrase detection identifies specific overused expressions that flag text as templated or generic. Phrases like "at the end of the day," "thinking outside the box," "in this day and age," "a wide variety of," and "plays a crucial role" are common in low-quality AI output and beginner writing. Identifying and replacing these phrases is one of the fastest ways to improve writing quality.

Suspicious Sections highlights specific passages that stand out as potentially copied or AI-generated within your text. This is particularly useful for mixed content \u2014 if you wrote most of an essay yourself but pasted in a few AI-generated paragraphs, the AI is good at identifying which specific paragraphs feel different from the rest of your writing style.

The Combined Risk score gives you a single at-a-glance number that weighs all four signals together: AI Detection (40%), lack of Originality (30%), and Web Matches (30%). This is useful for quick decisions \u2014 anything above 70% deserves serious review before submission, while scores below 20% suggest your writing is in good shape.

The web search component uses Brave Search\u2019s API to query the live, current web. Unlike static databases that may be months or years out of date, this means we are checking against the most recent version of the internet. The search uses exact-phrase matching with quotes, so even slight rewording can hide a match \u2014 this is intentional, as it minimizes false positives. If you want to detect paraphrased content, the AI Originality score is more sensitive to that.

This tool is honest about its limitations. We do not have access to academic databases like Turnitin or iThenticate, which means we cannot match against unpublished student papers, paywalled journals, or proprietary databases. For high-stakes academic submissions, we recommend using your institution\u2019s tool. But for everyday plagiarism checking \u2014 verifying blog posts, freelance work, content you commissioned, or your own drafts \u2014 the combination of AI detection plus live web search covers the vast majority of cases at zero cost.`;

export default function PlagiarismCheckerPage() {
  return (
    <div className="min-h-screen">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'BreadcrumbList',
            itemListElement: [
              { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://makersilo.com/' },
              { '@type': 'ListItem', position: 2, name: 'Converters', item: 'https://makersilo.com/converters/' },
              { '@type': 'ListItem', position: 3, name: 'Plagiarism Checker', item: 'https://makersilo.com/converters/plagiarism-checker/' },
            ],
          }),
        }}
      />

      <ToolSchema
        name="Free Plagiarism Checker"
        description="Free hybrid plagiarism checker that combines AI detection with live web search. Detects AI-generated content and finds matching web sources."
        url="https://makersilo.com/converters/plagiarism-checker/"
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <div className="flex flex-col xl:flex-row gap-8">
          <div className="flex-1 min-w-0">
            <h1 className="text-3xl sm:text-4xl font-bold text-white mb-3">
              Free Plagiarism Checker
            </h1>
            <p className="text-gray-400 text-lg mb-8 max-w-2xl">
              Hybrid plagiarism detection powered by AI analysis and live web search. Detect AI-generated content, find matching web sources, and check originality \u2014 all in one free tool.
            </p>

            <AdSlot position="above-tool" />

            <PlagiarismCheckerClient />

            <HowToUse keyword="Plagiarism Checker" steps={steps} />
            <FAQSection faqs={faqs} keyword="Plagiarism Checker" />
            <LongContent content={longContent} keyword="Plagiarism Checker" />

            <AdSlot position="below-content" />
          </div>

          <div className="hidden xl:block w-[300px] shrink-0">
            <div className="sticky top-24">
              <AdSlot position="sidebar" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
